const sourcedArticles = [
  { id: 'signal-001', title: 'NVIDIA Nemotron 3 Embed Ranks #1 Overall on RTEB, Advancing Agentic Retrieval', url: 'https://huggingface.co/blog/nvidia/nemotron-3-embed-wins-rteb', source: 'Hugging Face', topic: '检索与 RAG', scheduledDate: '2026-07-21' },
  { id: 'signal-002', title: 'Building a restaurant telephony AI host with Amazon Bedrock AgentCore and Amazon Nova 2 Sonic', url: 'https://aws.amazon.com/blogs/machine-learning/building-a-restaurant-telephony-ai-host-with-amazon-bedrock-agentcore-and-amazon-nova-2-sonic/', source: 'AWS ML Blog', topic: 'Agent 工程', scheduledDate: '2026-07-24' },
  { id: 'signal-003', title: 'Building scalable AI agents with modular prompt transpilation', url: 'https://developers.googleblog.com/building-scalable-ai-agents-with-modular-prompt-transpilation/', source: 'Google Developers', topic: 'Agent 工程', scheduledDate: '2026-07-28' },
  { id: 'signal-004', title: 'Integrating Context-Aware Video AI Agents Into Enterprise Workflows', url: 'https://developer.nvidia.com/blog/integrating-context-aware-video-ai-agents-into-enterprise-workflows/', source: 'NVIDIA Developer', topic: '多模态', scheduledDate: '2026-07-31' },
  { id: 'signal-005', title: 'Introducing Precursor: detecting agentic behavior with continuous client-side signals', url: 'https://blog.cloudflare.com/introducing-precursor/', source: 'Cloudflare', topic: 'Agent 工程', scheduledDate: '2026-08-04' },
  { id: 'signal-006', title: 'Aurora 1.5: Extending open foundation models for weather and Earth-system applications', url: 'https://www.microsoft.com/en-us/research/blog/aurora-1-5-extending-open-foundation-models-for-weather-and-earth-system-applications/', source: 'Microsoft Research', topic: 'Agent 工程', scheduledDate: '2026-08-07' },
  { id: 'signal-007', title: 'Newer Models, Same Advantage', url: 'https://huggingface.co/blog/Dharma-AI/newer-models-same-advantages', source: 'Hugging Face', topic: 'Agent 工程', scheduledDate: '2026-08-11' },
  { id: 'signal-008', title: 'Built Technologies builds an AI-powered document intelligence solution on AWS to power agents across real estate finance', url: 'https://aws.amazon.com/blogs/machine-learning/built-technologies-builds-an-ai-powered-document-intelligence-solution-on-aws-to-power-agents-across-real-estate-finance/', source: 'AWS ML Blog', topic: '数据工程', scheduledDate: '2026-08-14' },
  { id: 'signal-009', title: 'Expanding Choice in Gemini Enterprise Agent Platform: Introducing Grounding with Parallel Web Search', url: 'https://developers.googleblog.com/expanding-choice-in-gemini-enterprise-agent-platform-introducing-grounding-with-parallel-web-search/', source: 'Google Developers', topic: '检索与 RAG', scheduledDate: '2026-08-18' },
  { id: 'signal-010', title: 'Scaling Agentic AI Factories Through Extreme Co-Design with NVIDIA BlueField', url: 'https://developer.nvidia.com/blog/scaling-agentic-ai-factories-through-extreme-co-design-with-nvidia-bluefield/', source: 'NVIDIA Developer', topic: 'Agent 工程', scheduledDate: '2026-08-21' },
  { id: 'signal-011', title: 'Making AI search smarter', url: 'https://blog.cloudflare.com/making-ai-search-smarter/', source: 'Cloudflare', topic: '检索与 RAG', scheduledDate: '2026-08-25' },
  { id: 'signal-012', title: 'Flint: A visualization language for the AI era', url: 'https://www.microsoft.com/en-us/research/blog/flint-a-visualization-language-for-the-ai-era/', source: 'Microsoft Research', topic: 'Agent 工程', scheduledDate: '2026-08-28' },
  { id: 'signal-013', title: 'What building Shippy taught us about building agents', url: 'https://huggingface.co/blog/allenai/shippy-tech-blog', source: 'Hugging Face', topic: 'Agent 工程', scheduledDate: '2026-09-01' },
  { id: 'signal-014', title: 'Agentic vision: Building visual intelligence with Amazon Bedrock and MCP servers', url: 'https://aws.amazon.com/blogs/machine-learning/agentic-vision-building-visual-intelligence-with-amazon-bedrock-and-mcp-servers/', source: 'AWS ML Blog', topic: '多模态', scheduledDate: '2026-09-04' },
  { id: 'signal-015', title: "LiteRT.js, Google's high performance Web AI Inference", url: 'https://developers.googleblog.com/litertjs-googles-high-performance-web-ai-inference/', source: 'Google Developers', topic: '推理与性能', scheduledDate: '2026-09-08' },
  { id: 'signal-016', title: 'Develop Lightweight USD Runtimes Faster with AI Agents', url: 'https://developer.nvidia.com/blog/develop-lightweight-usd-runtimes-faster-with-ai-agents/', source: 'NVIDIA Developer', topic: 'Agent 工程', scheduledDate: '2026-09-11' },
  { id: 'signal-017', title: 'Your site, your rules: new AI traffic options for all customers', url: 'https://blog.cloudflare.com/content-independence-day-ai-options/', source: 'Cloudflare', topic: 'Agent 工程', scheduledDate: '2026-09-15' },
  { id: 'signal-018', title: 'SkillOpt: Agent skills as trainable parameters', url: 'https://www.microsoft.com/en-us/research/blog/skillopt-agent-skills-as-trainable-parameters/', source: 'Microsoft Research', topic: '训练与评测', scheduledDate: '2026-09-18' },
  { id: 'signal-019', title: 'Model Routing Is Simple. Until It Isn’t.', url: 'https://huggingface.co/blog/ibm-research/model-routing-is-simple-until-it-isnt', source: 'Hugging Face', topic: 'Agent 工程', scheduledDate: '2026-09-22' },
  { id: 'signal-020', title: 'Monitor Amazon SageMaker Pipelines cross-account with custom Amazon CloudWatch dashboards', url: 'https://aws.amazon.com/blogs/machine-learning/monitor-amazon-sagemaker-pipelines-cross-account-with-custom-amazon-cloudwatch-dashboards/', source: 'AWS ML Blog', topic: 'Agent 工程', scheduledDate: '2026-09-25' },
  { id: 'signal-021', title: 'Bridging the Domain Gap: AI Race Coach built with Antigravity and Gemini', url: 'https://developers.googleblog.com/bridging-the-domain-gap-ai-race-coach-built-with-antigravity-and-gemini/', source: 'Google Developers', topic: 'Agent 工程', scheduledDate: '2026-09-29' },
  { id: 'signal-022', title: 'Holo3.1: Fast & Local Computer Use Agents', url: 'https://huggingface.co/blog/Hcompany/holo31', source: 'Hugging Face', topic: 'Agent 工程' },
  { id: 'signal-023', title: 'Content Independence Day, one year on: building the business model for the agentic Internet', url: 'https://blog.cloudflare.com/agentic-internet-bot-report/', source: 'Cloudflare', topic: 'Agent 工程', scheduledDate: '2026-10-06' },
  { id: 'signal-024', title: 'Memora: A Harmonic Memory Representation Balancing Abstraction and Specificity', url: 'https://www.microsoft.com/en-us/research/blog/memora-a-harmonic-memory-representation-balancing-abstraction-and-specificity/', source: 'Microsoft Research', topic: 'Agent 工程', scheduledDate: '2026-10-09' },
  { id: 'signal-025', title: 'Introducing Real World VoiceEQ: Measuring the human quality of voice AI', url: 'https://huggingface.co/blog/real-world-voiceeq', source: 'Hugging Face', topic: '多模态', scheduledDate: '2026-10-13' },
  { id: 'signal-026', title: 'Multi-agent social intelligence with Strands Agents and Amazon Bedrock', url: 'https://aws.amazon.com/blogs/machine-learning/multi-agent-social-intelligence-with-strands-agents-and-amazon-bedrock/', source: 'AWS ML Blog', topic: 'Agent 工程', scheduledDate: '2026-10-16' },
  { id: 'signal-027', title: 'We terminated a TPU mid-training and it recovered in seconds: Introduction to elastic training with MaxText', url: 'https://developers.googleblog.com/we-terminated-a-tpu-mid-training-and-it-recovered-in-seconds-introduction-to-elastic-training-with-maxtext/', source: 'Google Developers', topic: '训练与评测', scheduledDate: '2026-10-20' },
  { id: 'signal-028', title: 'Lessons From the Leaderboard: What 5,000+ Kagglers Taught Us About Improving AI Reasoning', url: 'https://developer.nvidia.com/blog/lessons-from-the-leaderboard-what-5000-kagglers-taught-us-about-improving-ai-reasoning/', source: 'NVIDIA Developer', topic: '训练与评测', scheduledDate: '2026-10-23' },
  { id: 'signal-029', title: 'Temporary Cloudflare Accounts for AI agents', url: 'https://blog.cloudflare.com/temporary-accounts/', source: 'Cloudflare', topic: 'Agent 工程', scheduledDate: '2026-10-27' },
  { id: 'signal-030', title: 'Understanding the brain with AI-driven explanations and experiments', url: 'https://www.microsoft.com/en-us/research/blog/understanding-the-brain-with-ai-driven-explanations-and-experiments/', source: 'Microsoft Research', topic: 'Agent 工程', scheduledDate: '2026-10-30' },
  { id: 'signal-031', title: 'Profiling in PyTorch (Part 3): Attention is all you profile', url: 'https://huggingface.co/blog/torch-attention-profile', source: 'Hugging Face', topic: '推理与性能', scheduledDate: '2026-11-03' },
  { id: 'signal-032', title: 'Accelerating software delivery with agentic QA automation using Amazon Nova Act – Part 2', url: 'https://aws.amazon.com/blogs/machine-learning/accelerating-software-delivery-with-agentic-qa-automation-using-amazon-nova-act-part-2/', source: 'AWS ML Blog', topic: 'Agent 工程', scheduledDate: '2026-11-06' },
  { id: 'signal-033', title: 'Build agentic full-stack apps with Genkit', url: 'https://developers.googleblog.com/build-agentic-full-stack-apps-with-genkit/', source: 'Google Developers', topic: 'Agent 工程', scheduledDate: '2026-11-10' },
  { id: 'signal-034', title: 'How to Run an Autoresearch Workflow with RL Agent Skills and NVIDIA NeMo', url: 'https://developer.nvidia.com/blog/how-to-run-an-autoresearch-workflow-with-rl-agent-skills-and-nvidia-nemo/', source: 'NVIDIA Developer', topic: '检索与 RAG', scheduledDate: '2026-11-13' },
  { id: 'signal-035', title: 'Bringing more agent harnesses and frameworks to Cloudflare, starting with Flue', url: 'https://blog.cloudflare.com/agents-platform-flue-sdk/', source: 'Cloudflare', topic: 'Agent 工程', scheduledDate: '2026-11-17' },
  { id: 'signal-036', title: 'Data Formulator 0.7: AI-powered data analytics for enterprise data', url: 'https://www.microsoft.com/en-us/research/blog/data-formulator-0-7-ai-powered-data-analytics-for-enterprise-data/', source: 'Microsoft Research', topic: '数据工程', scheduledDate: '2026-11-20' },
  { id: 'signal-037', title: 'Native-speed vLLM transformers modeling backend', url: 'https://huggingface.co/blog/native-speed-vllm-transformers-backend', source: 'Hugging Face', topic: '推理与性能', scheduledDate: '2026-11-24' },
  { id: 'signal-038', title: 'Scaling medical content review at Flo Health with Amazon Bedrock – Part 2', url: 'https://aws.amazon.com/blogs/machine-learning/scaling-medical-content-review-at-flo-health-with-amazon-bedrock-part-2/', source: 'AWS ML Blog', topic: 'Agent 工程', scheduledDate: '2026-11-27' },
  { id: 'signal-039', title: 'Driving the Agent Quality Flywheel from Your Coding Agent', url: 'https://developers.googleblog.com/driving-the-agent-quality-flywheel-from-your-coding-agent/', source: 'Google Developers', topic: 'Agent 工程', scheduledDate: '2026-12-01' },
  { id: 'signal-040', title: 'Post-Train NVIDIA Cosmos 3 in One Day Using Agent Skills', url: 'https://developer.nvidia.com/blog/post-train-nvidia-cosmos-3-in-one-day-using-agent-skills/', source: 'NVIDIA Developer', topic: '训练与评测', scheduledDate: '2026-12-04' },
  { id: 'signal-041', title: 'Harness, Scaffold, and the AI Agent Terms Worth Getting Right', url: 'https://huggingface.co/blog/agent-glossary', source: 'Hugging Face', topic: 'Agent 工程' },
  { id: 'signal-042', title: 'Extending Human Intelligence Through AI', url: 'https://www.microsoft.com/en-us/research/blog/extending-human-intelligence-through-ai/', source: 'Microsoft Research', topic: 'Agent 工程', scheduledDate: '2026-12-11' },
  { id: 'signal-043', title: 'From Hugging Face to Amazon SageMaker Studio in one click', url: 'https://huggingface.co/blog/amazon/one-click-to-sagemaker-studio', source: 'Hugging Face', topic: 'Agent 工程', scheduledDate: '2026-12-15' },
  { id: 'signal-044', title: 'ScienceSoft’s HIPAA-compliant AI voice scheduler built on AWS', url: 'https://aws.amazon.com/blogs/machine-learning/sciencesofts-hipaa-compliant-ai-voice-scheduler-built-on-aws/', source: 'AWS ML Blog', topic: '多模态', scheduledDate: '2026-12-18' },
  { id: 'signal-045', title: 'Build reliable multi-agent applications with ADK Go 2.0', url: 'https://developers.googleblog.com/announcing-adk-go-20/', source: 'Google Developers', topic: 'Agent 工程', scheduledDate: '2026-12-22' },
  { id: 'signal-046', title: 'Extreme Event Likelihoods with Guided Generative Models', url: 'https://developer.nvidia.com/blog/extreme-event-likelihoods-with-guided-generative-models/', source: 'NVIDIA Developer', topic: 'Agent 工程', scheduledDate: '2026-12-25' },
  { id: 'signal-047', title: "Defend against frontier cyber models: Cloudflare's architecture as customer zero", url: 'https://blog.cloudflare.com/frontier-model-defense/', source: 'Cloudflare', topic: '安全与治理', scheduledDate: '2026-12-29' },
  { id: 'signal-048', title: 'Hugging Face Models on Foundry Managed Compute', url: 'https://huggingface.co/blog/microsoft/foundry-managed-compute', source: 'Hugging Face', topic: 'Agent 工程', scheduledDate: '2027-01-01' },
  { id: 'signal-049', title: 'OpenAI GPT-5.6 Sol, Terra, and Luna are now generally available on Amazon Bedrock', url: 'https://aws.amazon.com/blogs/machine-learning/openai-gpt-5-6-sol-terra-and-luna-are-now-generally-available-on-amazon-bedrock/', source: 'AWS ML Blog', topic: 'Agent 工程', scheduledDate: '2027-01-05' },
  { id: 'signal-050', title: 'Build Cross-Language Multi-Agent Team with Google’s Agent Development Kit and A2A', url: 'https://developers.googleblog.com/build-cross-language-multi-agent-team-with-google-agent-development-kit-and-a2a/', source: 'Google Developers', topic: 'Agent 工程', scheduledDate: '2027-01-08' },
  { id: 'signal-051', title: 'How to Evaluate General-Purpose Robot Policies for Real-World Deployment', url: 'https://developer.nvidia.com/blog/how-to-evaluate-general-purpose-robot-policies-for-real-world-deployment/', source: 'NVIDIA Developer', topic: '训练与评测', scheduledDate: '2027-01-12' },
  { id: 'signal-052', title: 'Your AI bill is out of control. Cloudflare can fix it now.', url: 'https://blog.cloudflare.com/ai-gateway-spend-limits/', source: 'Cloudflare', topic: 'Agent 工程', scheduledDate: '2027-01-15' },
  { id: 'signal-053', title: 'Run AI workloads on any cloud, store on Hugging Face: zero-egress storage with SkyPilot', url: 'https://huggingface.co/blog/skypilot-hf-storage', source: 'Hugging Face', topic: '检索与 RAG', scheduledDate: '2027-01-19' },
  { id: 'signal-054', title: 'When your brain works differently, AI isn’t a luxury—it’s accessibility', url: 'https://aws.amazon.com/blogs/machine-learning/when-your-brain-works-differently-ai-isnt-a-luxury-its-accessibility/', source: 'AWS ML Blog', topic: 'Agent 工程', scheduledDate: '2027-01-22' },
  { id: 'signal-055', title: 'How A2A is Building a World of Collaborative Agents', url: 'https://developers.googleblog.com/how-a2a-is-building-a-world-of-collaborative-agents/', source: 'Google Developers', topic: 'Agent 工程', scheduledDate: '2027-01-26' },
  { id: 'signal-056', title: 'Reducing High-Bandwidth Memory Bottlenecks in JAX-Based LLM Training with Host Offloading', url: 'https://developer.nvidia.com/blog/reducing-high-bandwidth-memory-bottlenecks-in-jax-based-llm-training-with-host-offloading/', source: 'NVIDIA Developer', topic: '训练与评测', scheduledDate: '2027-01-29' },
  { id: 'signal-057', title: "How we built Cloudflare's data platform and an AI agent on top of it", url: 'https://blog.cloudflare.com/our-unified-data-platform/', source: 'Cloudflare', topic: '数据工程', scheduledDate: '2027-02-02' },
  { id: 'signal-058', title: 'LeRobot v0.6.0: Imagine, Evaluate, Improve', url: 'https://huggingface.co/blog/lerobot-release-v060', source: 'Hugging Face', topic: '训练与评测', scheduledDate: '2027-02-05' },
  { id: 'signal-059', title: 'Building an agentic AI solution at Bluesight with Amazon Bedrock', url: 'https://aws.amazon.com/blogs/machine-learning/building-an-agentic-ai-solution-at-bluesight-with-amazon-bedrock/', source: 'AWS ML Blog', topic: 'Agent 工程', scheduledDate: '2027-02-09' },
  { id: 'signal-060', title: 'A2UI + MCP Apps: Combining the best of declarative and custom agentic UIs', url: 'https://developers.googleblog.com/a2ui-and-mcp-apps/', source: 'Google Developers', topic: 'Agent 工程', scheduledDate: '2027-02-12' },
  { id: 'signal-061', title: 'Kernel Fusion in NVIDIA CUDA: Optimizing Memory Traffic and Launch Overhead', url: 'https://developer.nvidia.com/blog/kernel-fusion-in-nvidia-cuda-optimizing-memory-traffic-and-launch-overhead/', source: 'NVIDIA Developer', topic: '推理与性能', scheduledDate: '2027-02-16' },
  { id: 'signal-062', title: 'Announcing Claude Managed Agents on Cloudflare', url: 'https://blog.cloudflare.com/claude-managed-agents/', source: 'Cloudflare', topic: 'Agent 工程', scheduledDate: '2027-02-19' },
  { id: 'signal-063', title: 'Hugging Face and Cerebras bring Gemma 4 to real-time voice AI', url: 'https://huggingface.co/blog/cerebras-gemma4-voice-ai', source: 'Hugging Face', topic: '多模态', scheduledDate: '2027-02-23' },
  { id: 'signal-064', title: 'Implement on-behalf-of token exchange for multi-tenant agents with Amazon Bedrock AgentCore Gateway', url: 'https://aws.amazon.com/blogs/machine-learning/implement-on-behalf-of-token-exchange-for-multi-tenant-agents-with-amazon-bedrock-agentcore-gateway/', source: 'AWS ML Blog', topic: 'Agent 工程', scheduledDate: '2027-02-26' },
  { id: 'signal-065', title: 'Announcing the Agentic Resource Discovery specification', url: 'https://developers.googleblog.com/announcing-the-agentic-resource-discovery-specification/', source: 'Google Developers', topic: 'Agent 工程', scheduledDate: '2027-03-02' },
  { id: 'signal-066', title: 'AI Model Co-Design: Hardware-Friendly LLM Design', url: 'https://developer.nvidia.com/blog/ai-model-co-design-hardware-friendly-llm-design/', source: 'NVIDIA Developer', topic: 'Agent 工程', scheduledDate: '2027-03-05' },
  { id: 'signal-067', title: 'Agents can now create Cloudflare accounts, buy domains, and deploy', url: 'https://blog.cloudflare.com/agents-stripe-projects/', source: 'Cloudflare', topic: 'Agent 工程', scheduledDate: '2027-03-09' },
  { id: 'signal-068', title: 'ScarfBench: Benchmarking AI Agents for Enterprise Java Framework Migration', url: 'https://huggingface.co/blog/ibm-research/scarfbench', source: 'Hugging Face', topic: '训练与评测', scheduledDate: '2027-03-12' },
  { id: 'signal-069', title: 'Launching UI for generative AI inference recommendations in Amazon SageMaker AI', url: 'https://aws.amazon.com/blogs/machine-learning/launching-ui-for-generative-ai-inference-recommendations-in-amazon-sagemaker-ai/', source: 'AWS ML Blog', topic: '推理与性能', scheduledDate: '2027-03-16' },
  { id: 'signal-070', title: 'DiffusionGemma: The Developer Guide', url: 'https://developers.googleblog.com/diffusiongemma-the-developer-guide/', source: 'Google Developers', topic: 'Agent 工程', scheduledDate: '2027-03-19' },
  { id: 'signal-071', title: 'Accelerating End-to-End Co-Folding Performance with NVIDIA BioNeMo Agent Toolkit', url: 'https://developer.nvidia.com/blog/accelerating-end-to-end-co-folding-performance-with-nvidia-bionemo-agent-toolkit/', source: 'NVIDIA Developer', topic: '推理与性能', scheduledDate: '2027-03-23' },
  { id: 'signal-072', title: 'Orchestrating AI Code Review at scale', url: 'https://blog.cloudflare.com/ai-code-review/', source: 'Cloudflare', topic: 'Agent 工程', scheduledDate: '2027-03-26' },
  { id: 'signal-073', title: 'Featuring Every Eval Ever Results on Hugging Face Model Pages', url: 'https://huggingface.co/blog/eee-community-evals', source: 'Hugging Face', topic: '训练与评测', scheduledDate: '2027-03-30' },
  { id: 'signal-074', title: 'Fine-tune NVIDIA Nemotron 3 models with Amazon SageMaker AI serverless model customization', url: 'https://aws.amazon.com/blogs/machine-learning/fine-tune-nvidia-nemotron-3-models-with-amazon-sagemaker-ai-serverless-model-customization/', source: 'AWS ML Blog', topic: '训练与评测', scheduledDate: '2027-04-02' },
  { id: 'signal-075', title: 'Synthetic Data Generation for Financial AI Research with NVIDIA NeMo', url: 'https://developer.nvidia.com/blog/synthetic-data-generation-for-financial-ai-research-with-nvidia-nemo/', source: 'NVIDIA Developer', topic: '检索与 RAG', scheduledDate: '2027-04-06' },
  { id: 'signal-076', title: 'The AI engineering stack we built internally — on the platform we ship', url: 'https://blog.cloudflare.com/internal-ai-engineering-stack/', source: 'Cloudflare', topic: 'Agent 工程', scheduledDate: '2027-04-09' },
  { id: 'signal-077', title: 'DiScoFormer: One transformer for density and score, across distributions', url: 'https://huggingface.co/blog/allenai/discoformer', source: 'Hugging Face', topic: 'Agent 工程', scheduledDate: '2027-04-13' },
  { id: 'signal-078', title: 'Real-time dental image verification with Amazon SageMaker AI at Henry Schein One', url: 'https://aws.amazon.com/blogs/machine-learning/real-time-dental-image-verification-with-amazon-sagemaker-ai-at-henry-schein-one/', source: 'AWS ML Blog', topic: '多模态', scheduledDate: '2027-04-16' },
  { id: 'signal-079', title: 'Building Blocks for Foundation Model Training and Inference on AWS', url: 'https://huggingface.co/blog/amazon/foundation-model-building-blocks', source: 'Hugging Face', topic: '训练与评测' },
  { id: 'signal-080', title: 'Run a vLLM Server on HF Jobs in One Command', url: 'https://huggingface.co/blog/vllm-jobs', source: 'Hugging Face', topic: '推理与性能', scheduledDate: '2027-04-23' },
  { id: 'signal-081', title: 'Build a semantic layer for agentic AI on AWS with Stardog and Amazon Bedrock AgentCore', url: 'https://aws.amazon.com/blogs/machine-learning/build-a-semantic-layer-for-agentic-ai-on-aws-with-stardog-and-amazon-bedrock-agentcore/', source: 'AWS ML Blog', topic: 'Agent 工程', scheduledDate: '2027-04-27' },
  { id: 'signal-082', title: 'Create a LangChain Deep Agents Harness Profile for NVIDIA Nemotron 3 Ultra to Improve Performance', url: 'https://developer.nvidia.com/blog/create-a-langchain-deep-agents-harness-profile-for-nvidia-nemotron-3-ultra-to-improve-performance/', source: 'NVIDIA Developer', topic: '推理与性能', scheduledDate: '2027-04-30' },
  { id: 'signal-083', title: 'Accelerating Transformers Fine-Tuning with NVIDIA NeMo AutoModel', url: 'https://huggingface.co/blog/nvidia/accelerating-fine-tuning-nvidia-nemo-automodel', source: 'Hugging Face', topic: '训练与评测', scheduledDate: '2027-05-04' },
  { id: 'signal-084', title: 'Scaling agentic workflows with native case management in Amazon Quick Automate', url: 'https://aws.amazon.com/blogs/machine-learning/scaling-agentic-workflows-with-native-case-management-in-amazon-quick-automate/', source: 'AWS ML Blog', topic: 'Agent 工程', scheduledDate: '2027-05-07' },
  { id: 'signal-085', title: 'Adding MCP Tools to Reachy Mini', url: 'https://huggingface.co/blog/adding-mcp-tools-to-reachy-mini', source: 'Hugging Face', topic: '多模态' },
  { id: 'signal-086', title: 'Introducing the FFASR Leaderboard: Benchmarking ASR in the Real World', url: 'https://huggingface.co/blog/ffasr-leaderboard', source: 'Hugging Face', topic: '训练与评测', scheduledDate: '2027-05-14' },
  { id: 'signal-087', title: 'Deploying quantized models on Amazon SageMaker AI with Unsloth', url: 'https://aws.amazon.com/blogs/machine-learning/deploying-quantized-models-on-amazon-sagemaker-ai-with-unsloth/', source: 'AWS ML Blog', topic: '推理与性能', scheduledDate: '2027-05-18' },
  { id: 'signal-088', title: 'NVIDIA Vera CPU Boosts AI Factory Throughput to Accelerate Agentic Workloads', url: 'https://developer.nvidia.com/blog/nvidia-vera-cpu-boosts-ai-factory-throughput-to-accelerate-agentic-workloads/', source: 'NVIDIA Developer', topic: 'Agent 工程', scheduledDate: '2027-05-21' },
  { id: 'signal-089', title: 'Shipping huggingface_hub every week with AI, open tools, and a human in the loop', url: 'https://huggingface.co/blog/huggingface-hub-release-ci', source: 'Hugging Face', topic: 'Agent 工程', scheduledDate: '2027-05-25' },
  { id: 'signal-090', title: 'Develop Humanoid Robot Policies End-to-End with NVIDIA Isaac GR00T', url: 'https://developer.nvidia.com/blog/develop-humanoid-robot-policies-end-to-end-with-nvidia-isaac-gr00t/', source: 'NVIDIA Developer', topic: '多模态', scheduledDate: '2027-05-28' },
  { id: 'signal-091', title: 'Experimenting with the proposed Cross-Origin Storage API in Transformers.js', url: 'https://huggingface.co/blog/cross-origin-storage', source: 'Hugging Face', topic: '检索与 RAG', scheduledDate: '2027-06-01' },
  { id: 'signal-092', title: 'Maximize Spectral Efficiency with AI-Native RAN and NVIDIA AI Aerial', url: 'https://developer.nvidia.com/blog/maximize-spectral-efficiency-with-ai-native-ran-and-nvidia-ai-aerial/', source: 'NVIDIA Developer', topic: 'Agent 工程', scheduledDate: '2027-06-04' },
  { id: 'signal-093', title: 'We got local models to triage the OpenClaw repo for FREE!*', url: 'https://huggingface.co/blog/local-models-pr-triage', source: 'Hugging Face', topic: 'Agent 工程', scheduledDate: '2027-06-08' },
  { id: 'signal-094', title: 'Building an Analysis AI Agent for Industrial Alarm Management with NVIDIA Nemotron', url: 'https://developer.nvidia.com/blog/building-an-analysis-ai-agent-for-industrial-alarm-management-with-nvidia-nemotron/', source: 'NVIDIA Developer', topic: 'Agent 工程', scheduledDate: '2027-06-11' },
  { id: 'signal-095', title: 'MosaicLeaks: Can your research agent keep a secret?', url: 'https://huggingface.co/blog/ServiceNow/mosaicleaks', source: 'Hugging Face', topic: '安全与治理', scheduledDate: '2027-06-15' },
  { id: 'signal-096', title: 'Enhancing Goodput in Large-Scale LLM Training with Nonuniform Tensor Parallelism', url: 'https://developer.nvidia.com/blog/enhancing-goodput-in-large-scale-llm-training-with-nonuniform-tensor-parallelism/', source: 'NVIDIA Developer', topic: '训练与评测', scheduledDate: '2027-06-18' },
  { id: 'signal-097', title: 'Beyond LoRA: Can you beat the most popular fine-tuning technique?', url: 'https://huggingface.co/blog/peft-beyond-lora', source: 'Hugging Face', topic: '训练与评测', scheduledDate: '2027-06-22' },
  { id: 'signal-098', title: 'Is it agentic enough? Benchmarking open models on your own tooling', url: 'https://huggingface.co/blog/is-it-agentic-enough', source: 'Hugging Face', topic: '训练与评测', scheduledDate: '2027-06-25' },
  { id: 'signal-099', title: 'From the Hugging Face Hub to robot hardware with Strands Agents and LeRobot', url: 'https://huggingface.co/blog/amazon/strands-lerobot-hub-to-hardware', source: 'Hugging Face', topic: '多模态', scheduledDate: '2027-06-29' },
  { id: 'signal-100', title: 'Agentic Resource Discovery: Let agents search', url: 'https://huggingface.co/blog/agentic-resource-discovery-launch', source: 'Hugging Face', topic: '检索与 RAG', scheduledDate: '2027-07-02' },
];

const chineseTitles = [
  'NVIDIA Nemotron 3 Embed 登顶 RTEB：推进智能体检索',
  '用 Amazon Bedrock AgentCore 与 Nova 2 Sonic 构建餐厅电话 AI 接待员',
  '用模块化提示词转译构建可扩展的 AI 智能体',
  '将上下文感知视频 AI 智能体接入企业工作流',
  'Precursor：用连续客户端信号识别智能体行为',
  'Aurora 1.5：面向天气与地球系统扩展开源基础模型',
  '新一代模型，依然保持同样的优势',
  '用 AWS 构建服务于房地产金融智能体的 AI 文档智能方案',
  'Gemini 企业智能体平台：用并行 Web 搜索实现内容溯源',
  '通过 NVIDIA BlueField 的极致协同设计扩展智能体 AI 工厂',
  '让 AI 搜索更智能',
  'Flint：面向 AI 时代的可视化语言',
  '从 Shippy 的构建过程学习如何开发智能体',
  '智能体视觉：用 Amazon Bedrock 与 MCP 构建视觉智能',
  'LiteRT.js：Google 的高性能 Web 端 AI 推理方案',
  '借助 AI 智能体更快开发轻量级 USD 运行时',
  '网站自主权：面向 AI 流量的新控制选项',
  'SkillOpt：把智能体技能作为可训练参数',
  '模型路由看似简单，直到它不再简单',
  '用自定义 CloudWatch 仪表板跨账户监控 SageMaker 流水线',
  '用 Antigravity 与 Gemini 构建 AI 赛车教练',
  'Holo 3.1：快速、本地运行的计算机操作智能体',
  '智能体互联网的商业模式：内容独立日一周年复盘',
  'Memora：兼顾抽象与具体的谐波记忆表示',
  'VoiceEQ：衡量语音 AI 的真实人类体验质量',
  '用 Strands Agents 与 Amazon Bedrock 构建多智能体社交智能',
  '训练中主动终止 TPU 后数秒恢复：MaxText 弹性训练入门',
  '五千多名 Kaggle 参赛者带来的 AI 推理改进经验',
  '面向 AI 智能体的 Cloudflare 临时账户',
  '用 AI 驱动的解释与实验理解大脑',
  'PyTorch 性能分析（三）：注意力机制专项剖析',
  '用 Amazon Nova Act 的智能体 QA 自动化加速软件交付',
  '用 Genkit 构建智能体全栈应用',
  '用强化学习智能体技能与 NVIDIA NeMo 运行自动研究工作流',
  '把更多智能体 Harness 与框架带到 Cloudflare：从 Flue 开始',
  'Data Formulator 0.7：面向企业数据的 AI 分析',
  '原生速度的 vLLM Transformers 建模后端',
  '用 Amazon Bedrock 扩展医疗内容审核',
  '从编码智能体推动智能体质量飞轮',
  '使用智能体技能在一天内完成 NVIDIA Cosmos 3 后训练',
  'Harness、Scaffold 与 AI 智能体术语辨析',
  '用 AI 延伸人类智能',
  '一键从 Hugging Face 进入 Amazon SageMaker Studio',
  '基于 AWS 构建符合 HIPAA 的 AI 语音预约系统',
  '用 ADK Go 2.0 构建可靠的多智能体应用',
  '用引导式生成模型估计极端事件发生概率',
  '防御前沿网络攻击模型：Cloudflare 的“客户零号”架构',
  '在 Foundry 托管算力上运行 Hugging Face 模型',
  'OpenAI GPT-5.6 Sol、Terra 与 Luna 登陆 Amazon Bedrock',
  '用 Google ADK 与 A2A 构建跨语言多智能体团队',
  '如何评估面向真实部署的通用机器人策略',
  'AI 成本失控怎么办：用 Cloudflare 限制 AI 网关支出',
  '跨云运行 AI 工作负载，并用 Hugging Face 实现零出口费用存储',
  '当大脑的工作方式不同时，AI 是无障碍能力而非奢侈品',
  'A2A 如何构建智能体协作世界',
  '通过主机卸载降低 JAX 大模型训练的高带宽显存瓶颈',
  'Cloudflare 统一数据平台与其上的 AI 智能体是如何构建的',
  'LeRobot 0.6：想象、评估与改进',
  '用 Amazon Bedrock 构建 Bluesight 的智能体 AI 方案',
  'A2UI 与 MCP Apps：结合声明式和定制智能体界面',
  'NVIDIA CUDA 内核融合：优化内存流量与启动开销',
  'Cloudflare 推出 Claude 托管智能体',
  'Hugging Face 与 Cerebras 让 Gemma 4 支持实时语音 AI',
  '用 AgentCore Gateway 为多租户智能体实现代表用户的令牌交换',
  '智能体资源发现规范正式发布',
  'AI 模型协同设计：面向硬件的大模型设计',
  '智能体现在可以创建 Cloudflare 账户、购买域名并完成部署',
  'ScarfBench：面向企业 Java 框架迁移的 AI 智能体基准',
  '在 Amazon SageMaker AI 中使用生成式 AI 推理推荐界面',
  'DiffusionGemma 开发者指南',
  '用 NVIDIA BioNeMo 智能体工具包加速端到端共折叠',
  '大规模编排 AI 代码审查',
  '在 Hugging Face 模型页面展示 Every Eval Ever 评测结果',
  '用 SageMaker AI 无服务器模型定制微调 NVIDIA Nemotron 3',
  '用 NVIDIA NeMo 为金融 AI 研究生成合成数据',
  'Cloudflare 内部 AI 工程栈：构建于其自有平台之上',
  'DiScoFormer：跨分布统一密度与得分建模的 Transformer',
  '用 Amazon SageMaker AI 实时验证牙科影像',
  '在 AWS 上训练与推理基础模型的构建模块',
  '一条命令在 Hugging Face Jobs 上运行 vLLM 服务',
  '用 Stardog 与 AgentCore 为 AWS 智能体 AI 构建语义层',
  '为 NVIDIA Nemotron 3 Ultra 创建 LangChain Deep Agents Harness 配置',
  '用 NVIDIA NeMo AutoModel 加速 Transformers 微调',
  '用 Amazon Quick Automate 的原生案例管理扩展智能体工作流',
  '为 Reachy Mini 添加 MCP 工具',
  'FFASR 排行榜：在真实环境中评测自动语音识别',
  '用 Unsloth 在 Amazon SageMaker AI 上部署量化模型',
  'NVIDIA Vera CPU 提升 AI 工厂吞吐并加速智能体负载',
  '借助 AI、开放工具与人工审核实现 huggingface_hub 每周发布',
  '用 NVIDIA Isaac GR00T 端到端开发人形机器人策略',
  '在 Transformers.js 中试验跨源存储 API',
  '用 AI 原生无线接入网与 NVIDIA AI Aerial 提升频谱效率',
  '用本地模型免费分流 OpenClaw 仓库问题',
  '用 NVIDIA Nemotron 构建工业告警管理分析智能体',
  'MosaicLeaks：研究智能体能否保守秘密',
  '用非均匀张量并行提升大规模大模型训练有效吞吐',
  '超越 LoRA：挑战最流行的微调方法',
  '它足够“智能体化”吗：在自有工具上评测开源模型',
  '从 Hugging Face Hub 到机器人硬件：Strands Agents 与 LeRobot 实践',
  '智能体资源发现：让智能体学会搜索',
];

function buildPublicationDates(count) {
  const currentWeekMonday = new Date(Date.UTC(2026, 6, 13));
  const dates = [];
  let seed = 20260717;
  let week = 0;

  const random = () => {
    seed = (seed * 1664525 + 1013904223) >>> 0;
    return seed / 4294967296;
  };

  while (dates.length < count) {
    const weeklyCount = random() < 0.5 ? 1 : 2;
    const offsets = new Set(week === 0 ? [4] : []);
    const maxOffset = week === 0 ? 4 : 7;
    while (offsets.size < weeklyCount) offsets.add(Math.floor(random() * maxOffset));

    for (const offset of [...offsets].sort((a, b) => b - a)) {
      if (dates.length >= count) break;
      const date = new Date(currentWeekMonday);
      date.setUTCDate(date.getUTCDate() - week * 7 + offset);
      dates.push(date.toISOString().slice(0, 10));
    }
    week += 1;
  }

  return dates;
}

const publicationDates = buildPublicationDates(sourcedArticles.length);

export const curatedArticles = sourcedArticles.map((article, index) => ({
  ...article,
  title: chineseTitles[index],
  originalTitle: article.title,
  scheduledDate: publicationDates[index],
  citation: `${article.source} 原文页面`,
}));

export const curatedTopics = ['全部', ...new Set(curatedArticles.map((article) => article.topic))];
